token_type: word

optim: adamw
optim_conf:
    lr: 5.0e-5
    weight_decay: 1.0e-2
    betas: [0.9, 0.98]

accum_grad: 1

batch_size: 128 # 12.5 steps per epoch with 1600 samples
max_epoch: 1000

scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
    first_cycle_steps: 6000
    warmup_steps: 300
    max_lr: 5.0e-5
    min_lr: 5.0e-6

frontend: none
input_size: 1
normalize: none

# Initialization for the decoder
init: xavier_normal

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.1
    length_normalized_loss: true

batch_type: folded
unused_parameters: true
grad_clip: 1
patience: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1
use_amp: false
num_att_plot: 0
num_workers: 2

encoder: beats
encoder_conf:
    beats_ckpt_path: CHECKPOINT_PATH
    fbank_mean: 11.72215
    fbank_std: 10.60431
    beats_config:
        layer_wise_gradient_decay_ratio: 0.2
        encoder_layerdrop: 0.1
        dropout: 0.0
    specaug_config:
        apply_time_warp: true
        apply_freq_mask: false
        apply_time_mask: true
        time_mask_width_ratio_range:
        - 0
        - 0.06
        num_time_mask: 1
    roll_augment: true
    roll_interval: 16000
    use_weighted_representation: false

decoder: linear_decoder
decoder_conf:
    pooling: mean
    dropout: 0.1
