unused_parameters: true
init: xavier_normal

# batch_type: folded
batch_type: weighted
utt2weight_file: /compute/babel-11-13/sbharad2/beats_run/as2m_balanced_static/data/utt2weight
shuffle_within_batch: false
# Need large batch size to get good estimate
valid_batch_size: 1200
batch_size: 640 # over 8gpus, 3191 batches on 2M, 6315 batches
max_epoch: 8 # 16 # 50k steps

accum_grad: 1
grad_clip: 1

optim: adamw
optim_conf:
    lr: 1.0e-4
    weight_decay: 1.0e-2
    betas: [0.9, 0.98]

scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
    first_cycle_steps: 50000
    warmup_steps: 5000
    max_lr: 1.0e-4
    min_lr: 5.0e-6

patience: none
best_model_criterion:
-   - valid
    - mAP
    - max
keep_nbest_models: 1
use_amp: false  # whether to use automatic mixed precision
num_att_plot: 0
num_workers: 2 # dataloader workers

# freeze_param: [
#       "encoder.encoder",
#       "encoder.layer_norm",
#       "encoder.patch_embedding",
#       "encoder.post_extract_proj",
# ]

# BEATs implementation takes care of generating mel spectrogram, normalization and specaug
frontend: none
input_size: 1 # important to set input_size to 1 if frontend is none
normalize: none # BEATs code does global mean and variance normalization

encoder: beats
encoder_conf:
    # Please download the BEATs model from https://github.com/microsoft/unilm/tree/master/beats
    # (iter3+, Beats finetuned model 1) and update the path below
    beats_ckpt_path: /compute/babel-13-33/sbharad2/models/BEATs/BEATs_iter3_plus_AS2M.pt # BEATs_iter3_plus_AS2M.pt # BEATs_iter3.pt
    beats_config:
        layer_wise_gradient_decay_ratio: 0.6
        encoder_layerdrop: 0.1
        dropout: 0.0
    use_weighted_representation: false
    specaug_config:
        apply_time_warp: true
        apply_freq_mask: false
        apply_time_mask: true
        time_mask_width_ratio_range:
        - 0
        - 0.06
        num_time_mask: 1
    roll_augment: true
    roll_interval: 1

model_conf:
    classification_type: multi-label
    mixup_augmentation: true
    lsm_weight: 0.0  # label smoothing weight, per label
