optim: adamw
optim_conf:
    lr: 1.0e-4
    weight_decay: 1.0e-2
    betas: [0.9, 0.98]

accum_grad: 1

batch_size: 128 # 12.5 steps per epoch with 1600 samples
max_epoch: 1000

scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
    first_cycle_steps: 6000
    warmup_steps: 300
    max_lr: 1.0e-4
    min_lr: 5.0e-6

frontend: none
input_size: 1
normalize: none

# Initialization for the decoder
init: xavier_normal

batch_type: folded
unused_parameters: true
grad_clip: 1
patience: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1
use_amp: false  # whether to use automatic mixed precision
num_att_plot: 0
num_workers: 2 # dataloader workers

encoder: dasheng
encoder_conf:
    model_name: DASHENG_MODEL_NAME
    specaug_config:
        apply_time_warp: true
        apply_freq_mask: false
        apply_time_mask: true
        time_mask_width_ratio_range:
        - 0
        - 0.06
        num_time_mask: 1
    roll_augment: true
    roll_interval: 16000

decoder: linear
decoder_conf:
    pooling: mean
    dropout: 0.1

model_conf:
    classification_type: multi-class
    lsm_weight: 0.1