token_type: word

optim: adamw
optim_conf:
    lr: 5.0e-5
    weight_decay: 1.0e-2
    betas: [0.9, 0.98]

accum_grad: 1

batch_size: 128 # 12.5 steps per epoch with 1600 samples
max_epoch: 1000

scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
    first_cycle_steps: 6000
    warmup_steps: 300
    max_lr: 5.0e-5
    min_lr: 5.0e-6

# BEATs implementation takes care of generating mel spectrogram, normalization and specaug
frontend: none
input_size: 1 # important to set input_size to 1 if frontend is none
normalize: none # BEATs code does global mean and variance normalization

# Initialization for the decoder
init: xavier_normal

model_conf:
    ctc_weight: 0.0  # No CTC, no attention.
    lsm_weight: 0.1  # label smoothing weight
    length_normalized_loss: true

batch_type: folded
unused_parameters: true
grad_clip: 1
patience: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 1
use_amp: false  # whether to use automatic mixed precision
num_att_plot: 0
num_workers: 2 # dataloader workers

encoder: beats
encoder_conf:
    beats_ckpt_path: /work/nvme/bbjs/sbharadwaj/7Msounds/exp/beats_iter0_huge0.tune_lr1.0e-4_warmup40000_bins2400000_totalsteps1600000/epoch98.pt
    fbank_mean: 11.72215
    fbank_std: 10.60431
    beats_config:
        layer_wise_gradient_decay_ratio: 0.4
        encoder_layerdrop: 0.2
        dropout: 0.1
    specaug_config:
        apply_time_warp: true
        apply_freq_mask: false
        apply_time_mask: true
        time_mask_width_ratio_range:
        - 0
        - 0.06
        num_time_mask: 1
    roll_augment: true
    roll_interval: 16000
    use_weighted_representation: false

# Simple linear decoder for classification.
decoder: linear_decoder
decoder_conf:
    pooling: mean
    dropout: 0.1
