# network architecture
# encoder related
encoder: hubert
encoder_conf:
    hubert_url: https://dl.fbaipublicfiles.com/hubert/hubert_large_ll60k.pt

# decoder related
decoder: transformer
decoder_conf:
    input_layer: "embed"
    num_blocks: 4
    linear_units: 1024
    dropout_rate: 0.1

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

# minibatch related
batch_type: folded
batch_size: 16

# optimization related
optim: adamw
accum_grad: 4
grad_clip: 5
patience: 15
max_epoch: 100
optim_conf:
    lr: 1.e-4
scheduler: linear
scheduler_conf:
    warmup_steps: 1000

# others:
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 1

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

init: xavier_uniform
