unused_parameters: true
init: xavier_normal

batch_type: folded
shuffle_within_batch: false
valid_batch_size: 32
batch_size: 32
max_epoch: 250

accum_grad: 1
grad_clip: 1

optim: adamw
optim_conf:
    lr: 3.0e-5 # 1.e-4
    weight_decay: 1.0e-2
    betas: [0.9, 0.98]

scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
    first_cycle_steps: 95000 # 80k steps
    warmup_steps: 8000
    max_lr: 3.0e-5 # 1.e-4
    min_lr: 5.0e-6

patience: none
best_model_criterion:
-   - valid
    - epoch_mAP
    - max
keep_nbest_models: 1
use_amp: false  # whether to use automatic mixed precision
num_att_plot: 0
num_workers: 2 # dataloader workers


frontend: none
input_size: 1
normalize: none

encoder: dasheng
encoder_conf:
    model_name: DASHENG_MODEL_NAME
    roll_augment: false
    specaug_config:
        apply_time_warp: true
        apply_freq_mask: false
        apply_time_mask: true
        time_mask_width_ratio_range:
        - 0
        - 0.06
        num_time_mask: 1

model_conf:
    classification_type: multi-label
    log_epoch_metrics: true
